#!/usr/bin/env bash
#display fizz,buzz and fizzbuzz for mutiple of 3,5 and both respectively

i=1
while ((i<101));
do
	if ((i%3==0 && i%5==0))
	then
		echo FizzBuzz
		((i+=1));
		continue
	elif ((i%3==0))
	then
		echo Fizz
		((i+=1));
		continue
	elif ((i%5==0))
	then
		echo Buzz
		((i+=1));
		continue
	else
		echo $i
		((i+=1));
	fi
done
