#!/usr/bin/env bash
# diplays Best School 10 time using while loop but for the
# nineth time it show hi

i=1
while ((i<=10));
do
	if ((i==9))
	then
		echo "Best School"
		echo "Hi"
	else ((i!=9))
		echo "Best School"
	fi
	((i+=1));
done

